import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from typing import List, Dict, Any

class PDFExporter:
    @staticmethod
    def export_chat_session(title: str, messages: List[Dict[str, Any]]) -> io.BytesIO:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=20,
            textColor=colors.HexColor("#1e293b"),
            spaceAfter=12
        )
        
        meta_style = ParagraphStyle(
            'DocMeta',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=20
        )
        
        user_header = ParagraphStyle(
            'UserHeader',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=12,
            textColor=colors.HexColor("#2563eb"),
            spaceAfter=4
        )

        ai_header = ParagraphStyle(
            'AIHeader',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=12,
            textColor=colors.HexColor("#0d9488"),
            spaceAfter=4
        )
        
        msg_body = ParagraphStyle(
            'MsgBody',
            parent=styles['BodyText'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
            spaceAfter=8
        )
        
        citation_style = ParagraphStyle(
            'CitationText',
            parent=styles['Italic'],
            fontName='Helvetica-Oblique',
            fontSize=9,
            textColor=colors.HexColor("#475569"),
            spaceAfter=4
        )

        story = []

        # Document Header
        story.append(Paragraph(f"RAG Chat Export: {title}", title_style))
        story.append(Paragraph("Generated by AI RAG Document Assistant", meta_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceAfter=15))

        for msg in messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            sources = msg.get("sources", [])

            # Format newlines for reportlab
            formatted_content = content.replace("\n", "<br/>")

            if role == "user":
                story.append(Paragraph("👤 User Question:", user_header))
                story.append(Paragraph(formatted_content, msg_body))
            else:
                story.append(Paragraph("🤖 AI Assistant Answer:", ai_header))
                story.append(Paragraph(formatted_content, msg_body))
                
                if sources:
                    story.append(Spacer(1, 4))
                    story.append(Paragraph("<b>Source Citations:</b>", citation_style))
                    for src in sources:
                        doc_name = src.get("document_name", "Document")
                        page_num = src.get("page_number", 1)
                        snippet = src.get("snippet", "")
                        src_text = f"• Document: <b>{doc_name}</b> (Page {page_num})<br/>&nbsp;&nbsp;<i>\"{snippet}\"</i>"
                        story.append(Paragraph(src_text, citation_style))
            
            story.append(Spacer(1, 12))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=12))

        doc.build(story)
        buffer.seek(0)
        return buffer
